version: '3.11'

services:
  # Simulateur API uniquement
  simulateur:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SIMULATEUR_PORT:-5000}:5000"
    networks:
      - kelo-network
    restart: unless-stopped
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - SIMULATEUR_PORT=5000
      - SIMULATEUR_HOST=0.0.0.0
    # Logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  kelo-network:
    driver: bridge
